name: Run tests

on:
  push:
    branches:
      - '**' # Matches any branch
  pull_request:
    branches:
      - '**' # Matches any branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true

    - name: Build
      run: cargo build

    - name: Run Tests
      run: cargo test

    - name: Upload test results
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: target/test
